apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: "capi-machine-webhook"
webhooks:
  - name: "default.machine.cluster.x-k8s.io"
    rules:
      - apiGroups:   ["cluster.x-k8s.io"]
        apiVersions: ["v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["machines/status"]
        scope:       "*"
      - apiGroups:   ["cluster.x-k8s.io"]
        apiVersions: ["v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["machines"]
        scope:       "*"
    clientConfig:
      service:
        namespace: "capi-machine-webhook"
        name: "capi-machine-webhook"
        path: /mutate-capi-machine
        port: 443
    admissionReviewVersions: ["v1"]
    failurePolicy: Ignore
    matchPolicy: Equivalent
    sideEffects: None
    timeoutSeconds: 5